[tool.pytest.ini_options]
pythonpath = "lib"
testpaths = "tests"
python_files = "*.py"
# required to catch exception in main()
log_level = "DEBUG"
addopts = "-v --cov=rift --cov-report=term-missing"

[tool.pylint.main]
# Specify a score threshold under which the program will exit with error.
fail-under = 9.80

# Minimum Python version to use for version dependent checks. Will default to the
# version used to run pylint.
py-version = "3.6"

[tool.pylint."messages control"]
# Disable the message, report, category or checker with the given id(s). You can
# either give multiple identifiers separated by comma (,) or put this option
# multiple times (only on the command line, not in the configuration file where
# it should appear only once). You can also use "--disable=all" to disable
# everything first and then re-enable specific checks. For example, if you want
# to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
#
# Currently disabled checkers are:
# E1101: Used when a variable is accessed for a nonexistent member.
# W0511: Used when a warning note as FIXME or XXX is detected.
disable = ["E1101", "W0511"]
