---
name: Automated Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

# Boostrap of the testing environment of this Python application cannot be
# performed the traditional way with actions/setup-python as some of the Python
# dependencies (rpm, dnf) are not available in PyPI, they are only distributed
# as system packages in major Linux distributions repositories. For this reason,
# containers are used with distribution package manager to install all
# dependencies.

jobs:
  tests:
    strategy:
      matrix:
        envs:
        - container: "almalinux/8-base"
          epel: 8
          ocean-repos: 3.8-1
        - container: "fedora"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.envs.container }}
      # --privileged for `mount`?
      options: --device=/dev/kvm
    steps:
      - uses: actions/checkout@v4

      # Does it need this virtual FS for /usr/bin/qemu-aarch64-static?
      # cat /proc/mounts
      # mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc

      # Required for mock
      - name: Enable EPEL repository
        if: ${{ startsWith(matrix.envs.container, 'almalinux') }}
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
          dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${{ matrix.envs.epel }}.noarch.rpm

      # Required for qemu
      - name: Enable Ocean repository
        if: ${{ startsWith(matrix.envs.container, 'almalinux') }}
        run:
          dnf -y install https://ocean.eupex.eu/install/ocean-repos-${{ matrix.envs.ocean-repos }}.x86_64.rpm

      - name: Install tests dependencies
        run: |
          dnf -y install python3-pip python3-jinja2 python3-PyYAML python3-rpm python3-dnf python3-pytest sudo rpm-sign rpmlint openssh-clients genisoimage qemu qemu-user qemu-img qemu-virtiofsd mock createrepo_c
          ls -lh /usr/bin/qemu*

      - name: Install application
        run: pip3 install -e .

      # Some tests expect to run as non-root with kvm, mock and sudo permissions
      # sudo required for sudo virtiosfd --version
      - name: Create unprivileged user
        run: |
          useradd ci
          usermod -aG $(stat -c %G /dev/kvm) ci
          usermod -aG mock ci
          echo "ci ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/00-ci

      - name: Run tests
        run: su ci -c 'pytest-3 -v'
