---
name: Automated Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  tests:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tests dependencies
        run: |
          sudo apt-get install -y python3-rpm gpg
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install application
        run: |
          pip install .

      - name: Run tests
        run: python3 -m unittest discover -s tests -p '*.py'
