---
name: Automated Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  tests:
    strategy:
      matrix:
        container: [ "almalinux/8-base" ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      options: --device=/dev/kvm
    steps:
      - uses: actions/checkout@v4

      - name: Enable EPEL
        run: |
          dnf -y install 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
          dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

      - name: Enable Ocean
        run:
          dnf -y install https://ocean.eupex.eu/install/ocean-repos-3.8-1.x86_64.rpm

      - name: Install tests dependencies
        run: |
          dnf -y install python3-pip python3-jinja2 python3-PyYAML python3-rpm python3-dnf python3-pytest rpm-sign rpmlint openssh-clients genisoimage qemu qemu-img mock createrepo_c

      # Some tests expect to run as non-root
      - name: Create unprivileged user
        run: |
          useradd ci
          usermod -aG kvm ci

      - name: Install application
        run: pip3 install --user -e .

      - name: Run tests
        run: su ci -c 'pytest-3'
