---
name: Automated Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  tests:
    strategy:
      matrix:
        containers: [ "almalinux/8-base" ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tests dependencies
        run: |
          dnf install python3-jinja2 python3-PyYAML python3-rpm python3-dnf rpm-sign openssh-clients genisoimage qemu qemu-img

      - name: Run tests
        run: pytest
